### PR TITLE
fix: signing key management

### LINKED ISSUE #67: bug: in-house generated tokens impose only one ExtAuthZ pod, due to private key generated at runtime.
### Describe the bug

Existing in memory, generating private and public keys for signing the in-house tokens introduces a scalability limitation, as it restricts the use to only one pod to behave correctly. 
    

### Expected Behaviour

ExtAuthZ is a critical component that should scale up and down without affecting any other components.

### Additional Context

**Solution:** The private and public key should be kept in Vault, and as a k8s secrets; The private key to be monted as volume to the ExtAuthZ. For CMK in need the public key for signature verification the public key will be mounted as volume as well!

### PR DESCRIPTION
**Pull request by cb80**
**What this PR does / why we need it**:
``` Detailed description of PR; If no description, remove the block.
Instead of generating a key pair in each pod, this PR changes the behavior
to load the private key from a file, so it can be centrally managed.
Additionally the loading is indirected using a keyID file, which allows us
to have multiple private keys for easy key rotation.
```

fixes #67

### CODE REVIEW

File: integration/main_test.go [hunk 1]
```diff
@@ -65,6 +66,56 @@ func init() {
...
+		cleanupFunc() // clean up any files written before the error
+		return cleanupFunc, fmt.Errorf("could not write file: %v, got: %s", configFile, err)
+	}
+	files = append(files, configFile)
+
+	// write trustedSubjects.yaml
+	trustedSubjectsYaml := "./trustedSubjects.yaml"
+	if err := os.WriteFile(trustedSubjectsYaml, []byte(trustedSubjects), 0640); err != nil {
+		cleanupFunc() // clean up any files written before the error
+		return cleanupFunc, fmt.Errorf("could not write file: %v, got: %s", trustedSubjectsYaml, err)
```
Comment (apatsap) [inline integration/main_test.go:90]: why do we return the `cleanupFunc` here when we have  already called it. I wouldn't return it but rather let it up to the function to cleanup after itself. 

Or, if you decide to return it then don't call it here

File: integration/main_test.go [hunk 2]
```diff
@@ -65,6 +66,56 @@ func init() {
...
+	files := []string{}
+	cleanupFunc := func() {
+		for _, file := range files {
+			os.Remove(file)
+		}
+	}
+
+	// write config.yaml
+	configFile := "./config.yaml"
+	if err := os.WriteFile(configFile, []byte(config), 0640); err != nil {
```
Comment (apatsap) [inline integration/main_test.go:80]: I think here is some potential to DRY this a bit, since we are repeating it 4 times.

Something like
```go
files := []struct{
   file string
   content string
}{ 
   {file: configFile, content: config}, 
   {file: trustedSubjectsYaml, content: trustedSubjects},
...
}

for _, f := range files {
     if err := os.WriteFile(f.file, []byte(f.content), 0640); err != nil {
         cleanupFunc() // clean up any files written before the error
		return cleanupFunc, fmt.Errorf("could not write file: %v, got: %s", f.file, err)
     }
	files = append(files, f.file)
}
```

File: integration/main_test.go [hunk 3]
```diff
@@ -65,6 +66,56 @@ func init() {
 	buildVersion = strings.TrimSpace(string(dat))
 }
 
+func writeFiles(config, trustedSubjects, policies, rsaPrivateKeyPEM string) (func(), error) {
+	// prepare the cleanup function to later remove files created during the test
+	files := []string{}
+	cleanupFunc := func() {
+		for _, file := range files {
+			os.Remove(file)
+		}
```
Comment (apatsap) [inline integration/main_test.go:75]: I'd add

```go
files = filed[:0]
```
just to make sure we don't call it necessarily twice.

**Review by apatsap — CHANGES_REQUESTED** [review]
just some small things

File: integration/main_test.go (hunk 1 above)
Comment (cb80) [reply integration/main_test.go]: Right, I changed it to return either a nil function + an error, or the cleanup function + no error.

File: integration/main_test.go (hunk 3 above)
Comment (cb80) [reply integration/main_test.go:85]: I switched to using channels. Let me know, what you think.

Comment (apatsap) [reply integration/main_test.go:85]: I was a bit unspecific. I meant to reset the slice after the loop. I.e.

```go
cleanupFunc := func() {
		for _, file := range cleanupFiles {
			log.Printf("removing file: %s", file)
			os.Remove(file)
		}
        cleanupFiles = cleanupFiles[:0]
}
```
Otherwise, we try to clean up already cleaned up files unnecessarily.

**Review by apatsap — CHANGES_REQUESTED** [review]
